# Broadcast probe configuration for WirePlumber 0.5 and newer.
wireplumber.profiles = {
  main = {
    monitor.bluez.seat-monitoring = disabled
  }
}

monitor.bluez.properties = {
  bluez5.roles = [ a2dp_sink a2dp_source ]
}

monitor.bluez.rules = [
  {
    matches = [
      { device.name = "~bluez_card.*" }
    ]
    actions = {
      update-props = {
        bluez5.auto-connect = [ a2dp_sink a2dp_source ]
      }
    }
  }
  {
    matches = [
      { node.name = "~bluez_input.*" }
    ]
    actions = {
      update-props = {
        bluez5.media-source-role = "input"
        node.pause-on-idle = false
        session.suspend-timeout-seconds = 0
      }
    }
  }
  {
    matches = [
      { node.name = "~bluez_output.*" }
    ]
    actions = {
      update-props = {
        node.pause-on-idle = false
        session.suspend-timeout-seconds = 0
      }
    }
  }
]
